CREATE TABLE BOOK_025(
    BOOK_ID CHAR(11) NOT NULL,
    SNO CHAR(5) NOT NULL,
    TITLE CHAR(31) NOT NULL,
    AUTHOR CHAR(31) NOT NULL,
    PUBLISHER CHAR(31),
    PRICE NUMBER(12, 2) CHECK(PRICE > 0),
    STATUS CHAR(1) DEFAULT 'A',
    PRIMARY KEY(BOOK_ID, SNO)
);

CREATE TABLE TYPE_DEPS_025(
    M_TYPE CHAR(1) CHECK(M_TYPE IN('S', 'F')) PRIMARY KEY,
    MAX_BOOKS NUMBER(2, 0) NOT NULL
);

 CREATE TABLE MEMBER_025(
    MEM_ID CHAR(10) PRIMARY KEY,
    NAME CHAR(31) NOT NULL,
    EMAIL CHAR(51),
    ADDR CHAR(51),
    M_TYPE CHAR(1) REFERENCES TYPE_DEPS_025(M_TYPE)
);

CREATE TABLE ISSUE_025(
    TR_ID CHAR(5) PRIMARY KEY,
    MEM_ID CHAR(10) REFERENCES MEMBER_025(MEM_ID),
    BOOK_ID CHAR(11) NOT NULL,
    SNO CHAR(5) NOT NULL,
    DT_ISSUE DATE NOT NULL,
    TO_RET_BY DATE,
    FOREIGN KEY(BOOK_ID, SNO) REFERENCES BOOK_025(BOOK_ID, SNO)
);

CREATE TABLE RETURN_025(
    TR_ID CHAR(5) PRIMARY KEY,
    MEM_ID CHAR(10) REFERENCES MEMBER_025(MEM_ID),
    BOOK_ID CHAR(11) NOT NULL,
    SNO CHAR(5) NOT NULL,
    DT_RETURN DATE,
    FOREIGN KEY(BOOK_ID, SNO) REFERENCES BOOK_025(BOOK_ID, SNO)
);
